// Chain configuration for blockchain dashboards
export interface ChainConfig {
  id: string;
  name: string;
  symbol: string;
  icon: string;
  color: string;
  tokens: string[];
  coingeckoId: string;
  explorerUrl: string;
  defiLlamaId?: string;
  dexScreenerId?: string;
  tps?: number;
  consensus?: string;
  nativeDecimals?: number;
  website?: string;
  twitter?: string;
  discord?: string;
  github?: string;
  docs?: string;
  category: "layer1" | "layer2" | "sidechain";
}

export const CHAINS: ChainConfig[] = [
  {
    id: "ethereum",
    name: "Ethereum",
    symbol: "ETH",
    icon: "⟠",
    color: "190 100% 50%",
    tokens: ["ETH", "LINK", "UNI", "AAVE", "LDO", "MKR", "CRV", "COMP", "ENS", "SNX", "RPL", "DYDX"],
    coingeckoId: "ethereum",
    explorerUrl: "https://etherscan.io",
    defiLlamaId: "ethereum",
    dexScreenerId: "ethereum",
    tps: 15,
    consensus: "Proof of Stake",
    nativeDecimals: 18,
    website: "https://ethereum.org",
    twitter: "https://twitter.com/ethereum",
    discord: "https://discord.gg/ethereum-org",
    github: "https://github.com/ethereum",
    docs: "https://ethereum.org/developers",
    category: "layer1",
  },
  {
    id: "solana",
    name: "Solana",
    symbol: "SOL",
    icon: "◎",
    color: "270 80% 60%",
    tokens: ["SOL", "RAY", "ORCA", "JTO", "PYTH", "JUP", "BONK", "WIF", "RENDER", "HNT"],
    coingeckoId: "solana",
    explorerUrl: "https://solscan.io",
    defiLlamaId: "solana",
    dexScreenerId: "solana",
    tps: 4000,
    consensus: "Proof of History + PoS",
    nativeDecimals: 9,
    website: "https://solana.com",
    twitter: "https://twitter.com/solana",
    discord: "https://discord.gg/solana",
    github: "https://github.com/solana-labs",
    docs: "https://docs.solana.com",
    category: "layer1",
  },
  {
    id: "bnb",
    name: "BNB Chain",
    symbol: "BNB",
    icon: "◆",
    color: "38 100% 50%",
    tokens: ["BNB", "CAKE", "XVS", "BAKE", "TWT", "ALPACA", "DODO", "VENUS"],
    coingeckoId: "binancecoin",
    explorerUrl: "https://bscscan.com",
    defiLlamaId: "bsc",
    dexScreenerId: "bsc",
    tps: 160,
    consensus: "Proof of Staked Authority",
    nativeDecimals: 18,
    website: "https://bnbchain.org",
    twitter: "https://twitter.com/BNBChain",
    github: "https://github.com/bnb-chain",
    docs: "https://docs.bnbchain.org",
    category: "layer1",
  },
  {
    id: "avalanche",
    name: "Avalanche",
    symbol: "AVAX",
    icon: "▲",
    color: "0 84% 60%",
    tokens: ["AVAX", "JOE", "PNG", "QI", "SPELL", "BENQI", "YAK", "GMX"],
    coingeckoId: "avalanche-2",
    explorerUrl: "https://snowtrace.io",
    defiLlamaId: "avax",
    dexScreenerId: "avalanche",
    tps: 4500,
    consensus: "Avalanche Consensus",
    nativeDecimals: 18,
    website: "https://avax.network",
    twitter: "https://twitter.com/avaboratory",
    discord: "https://discord.gg/avalanche",
    github: "https://github.com/ava-labs",
    docs: "https://docs.avax.network",
    category: "layer1",
  },
  {
    id: "polygon",
    name: "Polygon",
    symbol: "POL",
    icon: "⬡",
    color: "280 80% 55%",
    tokens: ["POL", "QUICK", "GHST", "SUSHI", "AAVE", "DFYN", "QI"],
    coingeckoId: "matic-network",
    explorerUrl: "https://polygonscan.com",
    defiLlamaId: "polygon",
    dexScreenerId: "polygon",
    tps: 7000,
    consensus: "Proof of Stake",
    nativeDecimals: 18,
    website: "https://polygon.technology",
    twitter: "https://twitter.com/0xPolygon",
    discord: "https://discord.gg/polygon",
    github: "https://github.com/maticnetwork",
    docs: "https://docs.polygon.technology",
    category: "sidechain",
  },
  {
    id: "arbitrum",
    name: "Arbitrum",
    symbol: "ARB",
    icon: "⬢",
    color: "210 90% 55%",
    tokens: ["ARB", "GMX", "MAGIC", "RDNT", "GNS", "PENDLE", "JONES", "DPX"],
    coingeckoId: "arbitrum",
    explorerUrl: "https://arbiscan.io",
    defiLlamaId: "arbitrum",
    dexScreenerId: "arbitrum",
    tps: 100,
    consensus: "Optimistic Rollup",
    nativeDecimals: 18,
    website: "https://arbitrum.io",
    twitter: "https://twitter.com/arbitrum",
    discord: "https://discord.gg/arbitrum",
    github: "https://github.com/OffchainLabs",
    docs: "https://docs.arbitrum.io",
    category: "layer2",
  },
  {
    id: "base",
    name: "Base",
    symbol: "ETH",
    icon: "◉",
    color: "220 90% 55%",
    tokens: ["ETH", "AERO", "BRETT", "DEGEN", "TOSHI", "HIGHER", "VIRTUAL"],
    coingeckoId: "ethereum",
    explorerUrl: "https://basescan.org",
    defiLlamaId: "base",
    dexScreenerId: "base",
    tps: 100,
    consensus: "Optimistic Rollup",
    nativeDecimals: 18,
    website: "https://base.org",
    twitter: "https://twitter.com/base",
    github: "https://github.com/base-org",
    docs: "https://docs.base.org",
    category: "layer2",
  },
  {
    id: "optimism",
    name: "Optimism",
    symbol: "OP",
    icon: "⨀",
    color: "0 100% 60%",
    tokens: ["OP", "VELO", "SNX", "PERP", "LYRA", "THALES"],
    coingeckoId: "optimism",
    explorerUrl: "https://optimistic.etherscan.io",
    defiLlamaId: "optimism",
    dexScreenerId: "optimism",
    tps: 100,
    consensus: "Optimistic Rollup",
    nativeDecimals: 18,
    website: "https://optimism.io",
    twitter: "https://twitter.com/Optimism",
    discord: "https://discord.gg/optimism",
    github: "https://github.com/ethereum-optimism",
    docs: "https://docs.optimism.io",
    category: "layer2",
  },
  {
    id: "sui",
    name: "Sui",
    symbol: "SUI",
    icon: "◈",
    color: "200 100% 55%",
    tokens: ["SUI", "CETUS", "TURBOS", "NAVI", "SCALLOP"],
    coingeckoId: "sui",
    explorerUrl: "https://suiscan.xyz",
    defiLlamaId: "sui",
    dexScreenerId: "sui",
    tps: 10000,
    consensus: "Delegated PoS",
    nativeDecimals: 9,
    website: "https://sui.io",
    twitter: "https://twitter.com/SuiNetwork",
    discord: "https://discord.gg/sui",
    github: "https://github.com/MystenLabs",
    docs: "https://docs.sui.io",
    category: "layer1",
  },
  {
    id: "ton",
    name: "TON",
    symbol: "TON",
    icon: "◇",
    color: "200 80% 50%",
    tokens: ["TON", "NOT", "DOGS", "HMSTR", "CATI"],
    coingeckoId: "the-open-network",
    explorerUrl: "https://tonscan.org",
    defiLlamaId: "ton",
    dexScreenerId: "ton",
    tps: 100000,
    consensus: "Proof of Stake",
    nativeDecimals: 9,
    website: "https://ton.org",
    twitter: "https://twitter.com/ton_blockchain",
    github: "https://github.com/ton-blockchain",
    docs: "https://docs.ton.org",
    category: "layer1",
  },
];

export const getChainById = (id: string): ChainConfig | undefined => {
  return CHAINS.find((chain) => chain.id === id);
};

export const getChainsByCategory = () => {
  return {
    layer1: CHAINS.filter(c => c.category === "layer1"),
    layer2: CHAINS.filter(c => c.category === "layer2"),
    sidechain: CHAINS.filter(c => c.category === "sidechain"),
  };
};
