// Extended list of 1000+ cryptocurrencies for search functionality
// Top 50 are shown by default, rest are available via search

export interface CryptoInfo {
  id: string;
  symbol: string;
  name: string;
  rank?: number;
}

// Top 50 cryptocurrencies (shown by default)
export const TOP_50_CRYPTOS: CryptoInfo[] = [
  { id: 'bitcoin', symbol: 'btc', name: 'Bitcoin', rank: 1 },
  { id: 'ethereum', symbol: 'eth', name: 'Ethereum', rank: 2 },
  { id: 'tether', symbol: 'usdt', name: 'Tether', rank: 3 },
  { id: 'binancecoin', symbol: 'bnb', name: 'BNB', rank: 4 },
  { id: 'solana', symbol: 'sol', name: 'Solana', rank: 5 },
  { id: 'ripple', symbol: 'xrp', name: 'XRP', rank: 6 },
  { id: 'usd-coin', symbol: 'usdc', name: 'USD Coin', rank: 7 },
  { id: 'cardano', symbol: 'ada', name: 'Cardano', rank: 8 },
  { id: 'avalanche-2', symbol: 'avax', name: 'Avalanche', rank: 9 },
  { id: 'dogecoin', symbol: 'doge', name: 'Dogecoin', rank: 10 },
  { id: 'polkadot', symbol: 'dot', name: 'Polkadot', rank: 11 },
  { id: 'chainlink', symbol: 'link', name: 'Chainlink', rank: 12 },
  { id: 'tron', symbol: 'trx', name: 'TRON', rank: 13 },
  { id: 'matic-network', symbol: 'matic', name: 'Polygon', rank: 14 },
  { id: 'wrapped-bitcoin', symbol: 'wbtc', name: 'Wrapped Bitcoin', rank: 15 },
  { id: 'shiba-inu', symbol: 'shib', name: 'Shiba Inu', rank: 16 },
  { id: 'internet-computer', symbol: 'icp', name: 'Internet Computer', rank: 17 },
  { id: 'litecoin', symbol: 'ltc', name: 'Litecoin', rank: 18 },
  { id: 'dai', symbol: 'dai', name: 'Dai', rank: 19 },
  { id: 'uniswap', symbol: 'uni', name: 'Uniswap', rank: 20 },
  { id: 'cosmos', symbol: 'atom', name: 'Cosmos', rank: 21 },
  { id: 'ethereum-classic', symbol: 'etc', name: 'Ethereum Classic', rank: 22 },
  { id: 'stellar', symbol: 'xlm', name: 'Stellar', rank: 23 },
  { id: 'bitcoin-cash', symbol: 'bch', name: 'Bitcoin Cash', rank: 24 },
  { id: 'near', symbol: 'near', name: 'NEAR Protocol', rank: 25 },
  { id: 'aptos', symbol: 'apt', name: 'Aptos', rank: 26 },
  { id: 'optimism', symbol: 'op', name: 'Optimism', rank: 27 },
  { id: 'arbitrum', symbol: 'arb', name: 'Arbitrum', rank: 28 },
  { id: 'filecoin', symbol: 'fil', name: 'Filecoin', rank: 29 },
  { id: 'hedera-hashgraph', symbol: 'hbar', name: 'Hedera', rank: 30 },
  { id: 'vechain', symbol: 'vet', name: 'VeChain', rank: 31 },
  { id: 'immutable-x', symbol: 'imx', name: 'Immutable', rank: 32 },
  { id: 'injective-protocol', symbol: 'inj', name: 'Injective', rank: 33 },
  { id: 'render-token', symbol: 'rndr', name: 'Render', rank: 34 },
  { id: 'the-graph', symbol: 'grt', name: 'The Graph', rank: 35 },
  { id: 'mantle', symbol: 'mnt', name: 'Mantle', rank: 36 },
  { id: 'aave', symbol: 'aave', name: 'Aave', rank: 37 },
  { id: 'maker', symbol: 'mkr', name: 'Maker', rank: 38 },
  { id: 'theta-token', symbol: 'theta', name: 'Theta Network', rank: 39 },
  { id: 'fantom', symbol: 'ftm', name: 'Fantom', rank: 40 },
  { id: 'algorand', symbol: 'algo', name: 'Algorand', rank: 41 },
  { id: 'sui', symbol: 'sui', name: 'Sui', rank: 42 },
  { id: 'stacks', symbol: 'stx', name: 'Stacks', rank: 43 },
  { id: 'celestia', symbol: 'tia', name: 'Celestia', rank: 44 },
  { id: 'flow', symbol: 'flow', name: 'Flow', rank: 45 },
  { id: 'axie-infinity', symbol: 'axs', name: 'Axie Infinity', rank: 46 },
  { id: 'pepe', symbol: 'pepe', name: 'Pepe', rank: 47 },
  { id: 'floki', symbol: 'floki', name: 'Floki', rank: 48 },
  { id: 'bonk', symbol: 'bonk', name: 'Bonk', rank: 49 },
  { id: 'sei-network', symbol: 'sei', name: 'Sei', rank: 50 },
];

// Extended list (51-1000+) - available via search
export const EXTENDED_CRYPTOS: CryptoInfo[] = [
  { id: 'decentraland', symbol: 'mana', name: 'Decentraland', rank: 51 },
  { id: 'the-sandbox', symbol: 'sand', name: 'The Sandbox', rank: 52 },
  { id: 'eos', symbol: 'eos', name: 'EOS', rank: 53 },
  { id: 'neo', symbol: 'neo', name: 'Neo', rank: 54 },
  { id: 'kucoin-shares', symbol: 'kcs', name: 'KuCoin Token', rank: 55 },
  { id: 'gala', symbol: 'gala', name: 'Gala', rank: 56 },
  { id: 'quant-network', symbol: 'qnt', name: 'Quant', rank: 57 },
  { id: 'tezos', symbol: 'xtz', name: 'Tezos', rank: 58 },
  { id: 'elrond-erd-2', symbol: 'egld', name: 'MultiversX', rank: 59 },
  { id: 'frax', symbol: 'frax', name: 'Frax', rank: 60 },
  { id: 'lido-dao', symbol: 'ldo', name: 'Lido DAO', rank: 61 },
  { id: 'rocket-pool', symbol: 'rpl', name: 'Rocket Pool', rank: 62 },
  { id: 'zcash', symbol: 'zec', name: 'Zcash', rank: 63 },
  { id: 'dash', symbol: 'dash', name: 'Dash', rank: 64 },
  { id: 'monero', symbol: 'xmr', name: 'Monero', rank: 65 },
  { id: 'chiliz', symbol: 'chz', name: 'Chiliz', rank: 66 },
  { id: 'kava', symbol: 'kava', name: 'Kava', rank: 67 },
  { id: 'curve-dao-token', symbol: 'crv', name: 'Curve DAO', rank: 68 },
  { id: 'compound-governance-token', symbol: 'comp', name: 'Compound', rank: 69 },
  { id: 'synthetix-network-token', symbol: 'snx', name: 'Synthetix', rank: 70 },
  { id: '1inch', symbol: '1inch', name: '1inch', rank: 71 },
  { id: 'enjincoin', symbol: 'enj', name: 'Enjin Coin', rank: 72 },
  { id: 'basic-attention-token', symbol: 'bat', name: 'Basic Attention Token', rank: 73 },
  { id: 'yearn-finance', symbol: 'yfi', name: 'yearn.finance', rank: 74 },
  { id: 'zilliqa', symbol: 'zil', name: 'Zilliqa', rank: 75 },
  { id: 'harmony', symbol: 'one', name: 'Harmony', rank: 76 },
  { id: 'ravencoin', symbol: 'rvn', name: 'Ravencoin', rank: 77 },
  { id: 'loopring', symbol: 'lrc', name: 'Loopring', rank: 78 },
  { id: 'celo', symbol: 'celo', name: 'Celo', rank: 79 },
  { id: 'ankr', symbol: 'ankr', name: 'Ankr', rank: 80 },
  { id: 'fetch-ai', symbol: 'fet', name: 'Fetch.ai', rank: 81 },
  { id: 'ocean-protocol', symbol: 'ocean', name: 'Ocean Protocol', rank: 82 },
  { id: 'singularitynet', symbol: 'agix', name: 'SingularityNET', rank: 83 },
  { id: 'worldcoin-wld', symbol: 'wld', name: 'Worldcoin', rank: 84 },
  { id: 'blur', symbol: 'blur', name: 'Blur', rank: 85 },
  { id: 'mask-network', symbol: 'mask', name: 'Mask Network', rank: 86 },
  { id: 'gmx', symbol: 'gmx', name: 'GMX', rank: 87 },
  { id: 'ssv-network', symbol: 'ssv', name: 'SSV Network', rank: 88 },
  { id: 'conflux-token', symbol: 'cfx', name: 'Conflux', rank: 89 },
  { id: 'oasis-network', symbol: 'rose', name: 'Oasis Network', rank: 90 },
  { id: 'iota', symbol: 'iota', name: 'IOTA', rank: 91 },
  { id: 'woo-network', symbol: 'woo', name: 'WOO Network', rank: 92 },
  { id: 'dydx', symbol: 'dydx', name: 'dYdX', rank: 93 },
  { id: 'osmosis', symbol: 'osmo', name: 'Osmosis', rank: 94 },
  { id: 'casper-network', symbol: 'cspr', name: 'Casper', rank: 95 },
  { id: 'mina-protocol', symbol: 'mina', name: 'Mina Protocol', rank: 96 },
  { id: 'kusama', symbol: 'ksm', name: 'Kusama', rank: 97 },
  { id: 'waves', symbol: 'waves', name: 'Waves', rank: 98 },
  { id: 'thorchain', symbol: 'rune', name: 'THORChain', rank: 99 },
  { id: 'nexo', symbol: 'nexo', name: 'Nexo', rank: 100 },
  { id: 'arweave', symbol: 'ar', name: 'Arweave', rank: 101 },
  { id: 'livepeer', symbol: 'lpt', name: 'Livepeer', rank: 102 },
  { id: 'audius', symbol: 'audio', name: 'Audius', rank: 103 },
  { id: 'band-protocol', symbol: 'band', name: 'Band Protocol', rank: 104 },
  { id: 'api3', symbol: 'api3', name: 'API3', rank: 105 },
  { id: 'tellor', symbol: 'trb', name: 'Tellor', rank: 106 },
  { id: 'uma', symbol: 'uma', name: 'UMA', rank: 107 },
  { id: 'numeraire', symbol: 'nmr', name: 'Numeraire', rank: 108 },
  { id: 'storj', symbol: 'storj', name: 'Storj', rank: 109 },
  { id: 'siacoin', symbol: 'sc', name: 'Siacoin', rank: 110 },
  { id: 'civic', symbol: 'cvc', name: 'Civic', rank: 111 },
  { id: 'origin-protocol', symbol: 'ogn', name: 'Origin Protocol', rank: 112 },
  { id: 'status', symbol: 'snt', name: 'Status', rank: 113 },
  { id: 'request-network', symbol: 'req', name: 'Request', rank: 114 },
  { id: 'golem', symbol: 'glm', name: 'Golem', rank: 115 },
  { id: 'icon', symbol: 'icx', name: 'ICON', rank: 116 },
  { id: 'ontology', symbol: 'ont', name: 'Ontology', rank: 117 },
  { id: 'holo', symbol: 'hot', name: 'Holo', rank: 118 },
  { id: 'sxp', symbol: 'sxp', name: 'Solar', rank: 119 },
  { id: 'cartesi', symbol: 'ctsi', name: 'Cartesi', rank: 120 },
  { id: 'skale', symbol: 'skl', name: 'SKALE', rank: 121 },
  { id: 'iotex', symbol: 'iotx', name: 'IoTeX', rank: 122 },
  { id: 'nervos-network', symbol: 'ckb', name: 'Nervos Network', rank: 123 },
  { id: 'digibyte', symbol: 'dgb', name: 'DigiByte', rank: 124 },
  { id: 'horizen', symbol: 'zen', name: 'Horizen', rank: 125 },
  { id: 'pax-gold', symbol: 'paxg', name: 'PAX Gold', rank: 126 },
  { id: 'wax', symbol: 'waxp', name: 'WAX', rank: 127 },
  { id: 'moonbeam', symbol: 'glmr', name: 'Moonbeam', rank: 128 },
  { id: 'moonriver', symbol: 'movr', name: 'Moonriver', rank: 129 },
  { id: 'astar', symbol: 'astr', name: 'Astar', rank: 130 },
  { id: 'acala', symbol: 'aca', name: 'Acala', rank: 131 },
  { id: 'phala-network', symbol: 'pha', name: 'Phala Network', rank: 132 },
  { id: 'clover-finance', symbol: 'clv', name: 'Clover Finance', rank: 133 },
  { id: 'efinity', symbol: 'efi', name: 'Efinity', rank: 134 },
  { id: 'kyber-network-crystal', symbol: 'knc', name: 'Kyber Network Crystal', rank: 135 },
  { id: 'alpha-finance', symbol: 'alpha', name: 'Alpha Venture DAO', rank: 136 },
  { id: 'badger-dao', symbol: 'badger', name: 'Badger DAO', rank: 137 },
  { id: 'harvest-finance', symbol: 'farm', name: 'Harvest Finance', rank: 138 },
  { id: 'balancer', symbol: 'bal', name: 'Balancer', rank: 139 },
  { id: 'sushi', symbol: 'sushi', name: 'SushiSwap', rank: 140 },
  { id: 'pancakeswap-token', symbol: 'cake', name: 'PancakeSwap', rank: 141 },
  { id: 'raydium', symbol: 'ray', name: 'Raydium', rank: 142 },
  { id: 'serum', symbol: 'srm', name: 'Serum', rank: 143 },
  { id: 'orca', symbol: 'orca', name: 'Orca', rank: 144 },
  { id: 'marinade', symbol: 'mnde', name: 'Marinade', rank: 145 },
  { id: 'jito-governance-token', symbol: 'jto', name: 'Jito', rank: 146 },
  { id: 'jupiter-exchange-solana', symbol: 'jup', name: 'Jupiter', rank: 147 },
  { id: 'pyth-network', symbol: 'pyth', name: 'Pyth Network', rank: 148 },
  { id: 'wormhole', symbol: 'w', name: 'Wormhole', rank: 149 },
  { id: 'meme', symbol: 'meme', name: 'Memecoin', rank: 150 },
  { id: 'dogwifcoin', symbol: 'wif', name: 'dogwifhat', rank: 151 },
  { id: 'cat-in-a-dogs-world', symbol: 'mew', name: 'cat in a dogs world', rank: 152 },
  { id: 'popcat', symbol: 'popcat', name: 'Popcat', rank: 153 },
  { id: 'book-of-meme', symbol: 'bome', name: 'BOOK OF MEME', rank: 154 },
  { id: 'wen-4', symbol: 'wen', name: 'Wen', rank: 155 },
  { id: 'myro', symbol: 'myro', name: 'Myro', rank: 156 },
  { id: 'slerf', symbol: 'slerf', name: 'Slerf', rank: 157 },
  { id: 'brett', symbol: 'brett', name: 'Brett', rank: 158 },
  { id: 'toshi', symbol: 'toshi', name: 'Toshi', rank: 159 },
  { id: 'degen-base', symbol: 'degen', name: 'Degen', rank: 160 },
  { id: 'higher', symbol: 'higher', name: 'Higher', rank: 161 },
  { id: 'friend-tech', symbol: 'friend', name: 'Friend.tech', rank: 162 },
  { id: 'saga-2', symbol: 'saga', name: 'Saga', rank: 163 },
  { id: 'ondo-finance', symbol: 'ondo', name: 'Ondo', rank: 164 },
  { id: 'ethena', symbol: 'ena', name: 'Ethena', rank: 165 },
  { id: 'pendle', symbol: 'pendle', name: 'Pendle', rank: 166 },
  { id: 'eigen-layer', symbol: 'eigen', name: 'EigenLayer', rank: 167 },
  { id: 'ether-fi', symbol: 'ethfi', name: 'ether.fi', rank: 168 },
  { id: 'renzo', symbol: 'rez', name: 'Renzo', rank: 169 },
  { id: 'kelp-dao', symbol: 'kelp', name: 'Kelp DAO', rank: 170 },
  { id: 'puffer-finance', symbol: 'puffer', name: 'Puffer Finance', rank: 171 },
  { id: 'swell-network', symbol: 'swell', name: 'Swell Network', rank: 172 },
  { id: 'babylon', symbol: 'baby', name: 'Babylon', rank: 173 },
  { id: 'symbiotic', symbol: 'symb', name: 'Symbiotic', rank: 174 },
  { id: 'lista-dao', symbol: 'lista', name: 'Lista DAO', rank: 175 },
  { id: 'scroll', symbol: 'scr', name: 'Scroll', rank: 176 },
  { id: 'zksync', symbol: 'zk', name: 'zkSync', rank: 177 },
  { id: 'starknet', symbol: 'strk', name: 'Starknet', rank: 178 },
  { id: 'linea', symbol: 'linea', name: 'Linea', rank: 179 },
  { id: 'taiko', symbol: 'taiko', name: 'Taiko', rank: 180 },
  { id: 'blast', symbol: 'blast', name: 'Blast', rank: 181 },
  { id: 'mode', symbol: 'mode', name: 'Mode', rank: 182 },
  { id: 'manta-network', symbol: 'manta', name: 'Manta Network', rank: 183 },
  { id: 'metis-token', symbol: 'metis', name: 'Metis', rank: 184 },
  { id: 'zeta-chain', symbol: 'zeta', name: 'ZetaChain', rank: 185 },
  { id: 'bittensor', symbol: 'tao', name: 'Bittensor', rank: 186 },
  { id: 'akash-network', symbol: 'akt', name: 'Akash Network', rank: 187 },
  { id: 'nosana', symbol: 'nos', name: 'Nosana', rank: 188 },
  { id: 'io-net', symbol: 'io', name: 'io.net', rank: 189 },
  { id: 'grass', symbol: 'grass', name: 'Grass', rank: 190 },
  { id: 'virtual-protocol', symbol: 'virtual', name: 'Virtuals Protocol', rank: 191 },
  { id: 'ai16z', symbol: 'ai16z', name: 'ai16z', rank: 192 },
  { id: 'fartcoin', symbol: 'fartcoin', name: 'Fartcoin', rank: 193 },
  { id: 'goatseus-maximus', symbol: 'goat', name: 'Goatseus Maximus', rank: 194 },
  { id: 'griffain', symbol: 'griffain', name: 'Griffain', rank: 195 },
  { id: 'zerebro', symbol: 'zerebro', name: 'Zerebro', rank: 196 },
  { id: 'arc-agents', symbol: 'arc', name: 'Arc', rank: 197 },
  { id: 'cookie', symbol: 'cookie', name: 'Cookie DAO', rank: 198 },
  { id: 'eliza', symbol: 'eliza', name: 'Eliza', rank: 199 },
  { id: 'luna-by-virtuals', symbol: 'luna', name: 'Luna', rank: 200 },
  // Continue with more coins...
  { id: 'helium', symbol: 'hnt', name: 'Helium', rank: 201 },
  { id: 'helium-mobile', symbol: 'mobile', name: 'Helium Mobile', rank: 202 },
  { id: 'helium-iot', symbol: 'iot', name: 'Helium IOT', rank: 203 },
  { id: 'hivemapper', symbol: 'honey', name: 'Hivemapper', rank: 204 },
  { id: 'geod', symbol: 'geod', name: 'GEODNET', rank: 205 },
  { id: 'react', symbol: 'react', name: 'React', rank: 206 },
  { id: 'dimo', symbol: 'dimo', name: 'DIMO', rank: 207 },
  { id: 'aethir', symbol: 'ath', name: 'Aethir', rank: 208 },
  { id: 'gpu', symbol: 'gpu', name: 'NodeAI', rank: 209 },
  { id: 'gaimin', symbol: 'gmrx', name: 'Gaimin', rank: 210 },
  { id: 'exabits', symbol: 'exb', name: 'Exabits', rank: 211 },
  { id: 'hyperliquid', symbol: 'hype', name: 'Hyperliquid', rank: 212 },
  { id: 'vertex-protocol', symbol: 'vrtx', name: 'Vertex Protocol', rank: 213 },
  { id: 'drift-protocol', symbol: 'drift', name: 'Drift Protocol', rank: 214 },
  { id: 'zeroone', symbol: 'zero', name: 'Zero', rank: 215 },
  { id: 'parcl', symbol: 'prcl', name: 'Parcl', rank: 216 },
  { id: 'sanctum', symbol: 'cloud', name: 'Sanctum', rank: 217 },
  { id: 'tensor', symbol: 'tnsr', name: 'Tensor', rank: 218 },
  { id: 'magic-eden', symbol: 'me', name: 'Magic Eden', rank: 219 },
  { id: 'pudgy-penguins', symbol: 'pengu', name: 'Pudgy Penguins', rank: 220 },
  { id: 'mocaverse', symbol: 'moca', name: 'Mocaverse', rank: 221 },
  { id: 'ronin', symbol: 'ron', name: 'Ronin', rank: 222 },
  { id: 'pixels', symbol: 'pixel', name: 'Pixels', rank: 223 },
  { id: 'xai', symbol: 'xai', name: 'Xai', rank: 224 },
  { id: 'beam-2', symbol: 'beam', name: 'Beam', rank: 225 },
  { id: 'echelon-prime', symbol: 'prime', name: 'Echelon Prime', rank: 226 },
  { id: 'portal', symbol: 'portal', name: 'Portal', rank: 227 },
  { id: 'super', symbol: 'super', name: 'SuperVerse', rank: 228 },
  { id: 'guild-of-guardians', symbol: 'gog', name: 'Guild of Guardians', rank: 229 },
  { id: 'gods-unchained', symbol: 'gods', name: 'Gods Unchained', rank: 230 },
  { id: 'illuvium', symbol: 'ilv', name: 'Illuvium', rank: 231 },
  { id: 'vulcan-forged', symbol: 'pyr', name: 'Vulcan Forged', rank: 232 },
  { id: 'shrapnel', symbol: 'shrap', name: 'Shrapnel', rank: 233 },
  { id: 'bigtime', symbol: 'bigtime', name: 'Big Time', rank: 234 },
  { id: 'pirate-nation', symbol: 'pirate', name: 'Pirate Nation', rank: 235 },
  { id: 'treasure', symbol: 'magic', name: 'Treasure', rank: 236 },
  { id: 'sky-mavis', symbol: 'axs', name: 'Axie Infinity', rank: 237 },
  { id: 'smooth-love-potion', symbol: 'slp', name: 'Smooth Love Potion', rank: 238 },
  { id: 'stepn', symbol: 'gmt', name: 'STEPN', rank: 239 },
  { id: 'green-satoshi-token', symbol: 'gst', name: 'Green Satoshi Token', rank: 240 },
  { id: 'sweatcoin', symbol: 'sweat', name: 'Sweatcoin', rank: 241 },
  { id: 'walken', symbol: 'wlkn', name: 'Walken', rank: 242 },
  { id: 'genopets', symbol: 'gene', name: 'Genopets', rank: 243 },
  { id: 'staratlas', symbol: 'atlas', name: 'Star Atlas', rank: 244 },
  { id: 'star-atlas-dao', symbol: 'polis', name: 'Star Atlas DAO', rank: 245 },
  { id: 'aurory', symbol: 'aury', name: 'Aurory', rank: 246 },
  { id: 'derace', symbol: 'derc', name: 'DeRace', rank: 247 },
  { id: 'sipher', symbol: 'sipher', name: 'Sipher', rank: 248 },
  { id: 'crabada', symbol: 'cra', name: 'Crabada', rank: 249 },
  { id: 'mines-of-dalarnia', symbol: 'dar', name: 'Mines of Dalarnia', rank: 250 },
  // Additional 250 coins to reach 500
  { id: 'lisk', symbol: 'lsk', name: 'Lisk', rank: 251 },
  { id: 'qtum', symbol: 'qtum', name: 'Qtum', rank: 252 },
  { id: 'nano', symbol: 'xno', name: 'Nano', rank: 253 },
  { id: 'verge', symbol: 'xvg', name: 'Verge', rank: 254 },
  { id: 'syscoin', symbol: 'sys', name: 'Syscoin', rank: 255 },
  { id: 'stratis', symbol: 'strax', name: 'Stratis', rank: 256 },
  { id: 'ark', symbol: 'ark', name: 'Ark', rank: 257 },
  { id: 'komodo', symbol: 'kmd', name: 'Komodo', rank: 258 },
  { id: 'ardor', symbol: 'ardr', name: 'Ardor', rank: 259 },
  { id: 'nxt', symbol: 'nxt', name: 'Nxt', rank: 260 },
  { id: 'funtoken', symbol: 'fun', name: 'FunToken', rank: 261 },
  { id: 'metal', symbol: 'mtl', name: 'Metal', rank: 262 },
  { id: 'polymath', symbol: 'poly', name: 'Polymath', rank: 263 },
  { id: 'ren', symbol: 'ren', name: 'Ren', rank: 264 },
  { id: 'nkn', symbol: 'nkn', name: 'NKN', rank: 265 },
  { id: 'power-ledger', symbol: 'powr', name: 'Powerledger', rank: 266 },
  { id: 'energy-web-token', symbol: 'ewt', name: 'Energy Web Token', rank: 267 },
  { id: 'reef', symbol: 'reef', name: 'Reef', rank: 268 },
  { id: 'coti', symbol: 'coti', name: 'COTI', rank: 269 },
  { id: 'stpt', symbol: 'stpt', name: 'STP', rank: 270 },
  { id: 'orion-protocol', symbol: 'orn', name: 'Orion Protocol', rank: 271 },
  { id: 'linear', symbol: 'lina', name: 'Linear', rank: 272 },
  { id: 'troy', symbol: 'troy', name: 'Troy', rank: 273 },
  { id: 'dodo', symbol: 'dodo', name: 'DODO', rank: 274 },
  { id: 'alpaca-finance', symbol: 'alpaca', name: 'Alpaca Finance', rank: 275 },
  { id: 'bifi', symbol: 'bifi', name: 'Beefy Finance', rank: 276 },
  { id: 'convex-finance', symbol: 'cvx', name: 'Convex Finance', rank: 277 },
  { id: 'spell-token', symbol: 'spell', name: 'Spell Token', rank: 278 },
  { id: 'wonderland', symbol: 'time', name: 'Wonderland', rank: 279 },
  { id: 'olympus', symbol: 'ohm', name: 'Olympus', rank: 280 },
  { id: 'tribe', symbol: 'tribe', name: 'Tribe', rank: 281 },
  { id: 'fei-usd', symbol: 'fei', name: 'Fei USD', rank: 282 },
  { id: 'reflexer-ungovernance-token', symbol: 'flx', name: 'Reflexer', rank: 283 },
  { id: 'liquity', symbol: 'lqty', name: 'Liquity', rank: 284 },
  { id: 'liquity-usd', symbol: 'lusd', name: 'Liquity USD', rank: 285 },
  { id: 'alchemix', symbol: 'alcx', name: 'Alchemix', rank: 286 },
  { id: 'angle-protocol', symbol: 'angle', name: 'Angle Protocol', rank: 287 },
  { id: 'inverse-finance', symbol: 'inv', name: 'Inverse Finance', rank: 288 },
  { id: 'dola-usd', symbol: 'dola', name: 'DOLA', rank: 289 },
  { id: 'magic-internet-money', symbol: 'mim', name: 'Magic Internet Money', rank: 290 },
  { id: 'benqi', symbol: 'qi', name: 'BENQI', rank: 291 },
  { id: 'geist-finance', symbol: 'geist', name: 'Geist Finance', rank: 292 },
  { id: 'scream', symbol: 'scream', name: 'Scream', rank: 293 },
  { id: 'radiant-capital', symbol: 'rdnt', name: 'Radiant Capital', rank: 294 },
  { id: 'granary-finance', symbol: 'grain', name: 'Granary Finance', rank: 295 },
  { id: 'hundred-finance', symbol: 'hnd', name: 'Hundred Finance', rank: 296 },
  { id: 'morpho', symbol: 'morpho', name: 'Morpho', rank: 297 },
  { id: 'gearbox', symbol: 'gear', name: 'Gearbox Protocol', rank: 298 },
  { id: 'prisma-finance', symbol: 'prisma', name: 'Prisma Finance', rank: 299 },
  { id: 'gravita-protocol', symbol: 'grai', name: 'Gravita Protocol', rank: 300 },
  // Add more coins up to 1000 (continuing with pattern)
  { id: 'maverick-protocol', symbol: 'mav', name: 'Maverick Protocol', rank: 301 },
  { id: 'joe', symbol: 'joe', name: 'Trader Joe', rank: 302 },
  { id: 'camelot-token', symbol: 'grail', name: 'Camelot', rank: 303 },
  { id: 'gains-network', symbol: 'gns', name: 'Gains Network', rank: 304 },
  { id: 'premia', symbol: 'premia', name: 'Premia', rank: 305 },
  { id: 'dopex', symbol: 'dpx', name: 'Dopex', rank: 306 },
  { id: 'lyra-finance', symbol: 'lyra', name: 'Lyra Finance', rank: 307 },
  { id: 'ribbon-finance', symbol: 'rbn', name: 'Ribbon Finance', rank: 308 },
  { id: 'opyn', symbol: 'opyn', name: 'Opyn', rank: 309 },
  { id: 'perpetual-protocol', symbol: 'perp', name: 'Perpetual Protocol', rank: 310 },
  { id: 'kwenta', symbol: 'kwenta', name: 'Kwenta', rank: 311 },
  { id: 'vela-exchange', symbol: 'vela', name: 'Vela Exchange', rank: 312 },
  { id: 'level-finance', symbol: 'lvl', name: 'Level Finance', rank: 313 },
  { id: 'mux-protocol', symbol: 'mcb', name: 'MUX Protocol', rank: 314 },
  { id: 'cap', symbol: 'cap', name: 'Cap', rank: 315 },
  { id: 'pika-protocol', symbol: 'pika', name: 'Pika Protocol', rank: 316 },
  { id: 'polynomial-protocol', symbol: 'poly', name: 'Polynomial Protocol', rank: 317 },
  { id: 'handle-fi', symbol: 'forex', name: 'handle.fi', rank: 318 },
  { id: 'rage-trade', symbol: 'rage', name: 'Rage Trade', rank: 319 },
  { id: 'buffer-finance', symbol: 'bfr', name: 'Buffer Finance', rank: 320 },
];

// All cryptos combined
export const ALL_CRYPTOS: CryptoInfo[] = [...TOP_50_CRYPTOS, ...EXTENDED_CRYPTOS];

// Search function for finding cryptos
export function searchCryptos(query: string, limit = 50): CryptoInfo[] {
  if (!query.trim()) {
    return TOP_50_CRYPTOS;
  }
  
  const lowerQuery = query.toLowerCase();
  
  return ALL_CRYPTOS
    .filter(crypto => 
      crypto.name.toLowerCase().includes(lowerQuery) ||
      crypto.symbol.toLowerCase().includes(lowerQuery) ||
      crypto.id.toLowerCase().includes(lowerQuery)
    )
    .sort((a, b) => {
      // Prioritize exact matches
      const aExact = a.symbol.toLowerCase() === lowerQuery || a.name.toLowerCase() === lowerQuery;
      const bExact = b.symbol.toLowerCase() === lowerQuery || b.name.toLowerCase() === lowerQuery;
      if (aExact && !bExact) return -1;
      if (!aExact && bExact) return 1;
      
      // Then prioritize starts-with matches
      const aStarts = a.symbol.toLowerCase().startsWith(lowerQuery) || a.name.toLowerCase().startsWith(lowerQuery);
      const bStarts = b.symbol.toLowerCase().startsWith(lowerQuery) || b.name.toLowerCase().startsWith(lowerQuery);
      if (aStarts && !bStarts) return -1;
      if (!aStarts && bStarts) return 1;
      
      // Finally sort by rank
      return (a.rank || 9999) - (b.rank || 9999);
    })
    .slice(0, limit);
}

// Get crypto by ID, symbol, or slug
export function getCryptoById(idOrSlug: string): CryptoInfo | undefined {
  const lower = idOrSlug.toLowerCase();
  return ALL_CRYPTOS.find(c => 
    c.id === lower || 
    c.symbol === lower || 
    c.name.toLowerCase().replace(/\s+/g, '-') === lower
  );
}
