project_id = "qynszkirmcrldqmiplwh"

[functions.crypto-prices]
verify_jwt = false

[functions.crypto-market]
verify_jwt = false

[functions.ai-forecast]
verify_jwt = false

[functions.chain-data]
verify_jwt = false

[functions.chain-forecast]
verify_jwt = false
