import { Layout } from "@/components/layout/Layout";
import { Helmet } from "react-helmet-async";

const Terms = () => {
  return (
    <Layout>
      <Helmet>
        <title>Terms of Service | Oracle Bull</title>
        <meta name="description" content="Oracle Bull terms of service — the terms and conditions for using our platform." />
      </Helmet>

      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <h1 className="text-3xl md:text-4xl font-display font-bold mb-8">Terms of Service</h1>
        <div className="space-y-6 text-sm text-muted-foreground leading-relaxed">
          <p className="text-xs text-muted-foreground">Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>

          <section>
            <h2 className="font-display font-bold text-lg text-foreground mb-2">1. Acceptance of Terms</h2>
            <p>By accessing or using Oracle Bull ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-lg text-foreground mb-2">2. Description of Service</h2>
            <p>Oracle Bull provides cryptocurrency analytics, AI-powered price predictions, market data, and educational tools. The Service is provided for informational and educational purposes only.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-lg text-foreground mb-2">3. Not Financial Advice</h2>
            <p>Nothing on this website constitutes financial, investment, trading, or tax advice. All predictions, analyses, and data are generated by AI models and algorithms and should not be relied upon for investment decisions. Always do your own research and consult a qualified financial advisor before making any investment decisions.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-lg text-foreground mb-2">4. No Guarantees</h2>
            <p>Oracle Bull makes no guarantees about the accuracy, completeness, or reliability of any information, predictions, or analysis provided through the Service. Past performance does not guarantee future results. Cryptocurrency markets are highly volatile and unpredictable.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-lg text-foreground mb-2">5. User Responsibilities</h2>
            <p>You are solely responsible for your own investment decisions and any consequences thereof. You agree not to hold Oracle Bull liable for any losses, damages, or expenses arising from your use of the Service or reliance on any information provided.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-lg text-foreground mb-2">6. Intellectual Property</h2>
            <p>All content, including text, graphics, logos, data, and software, is the property of Oracle Bull or its licensors and is protected by applicable intellectual property laws. You may not reproduce, distribute, or create derivative works without prior written consent.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-lg text-foreground mb-2">7. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, Oracle Bull shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your use of the Service.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-lg text-foreground mb-2">8. Modifications</h2>
            <p>Oracle Bull reserves the right to modify these terms at any time. Continued use of the Service after changes constitutes acceptance of the modified terms.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-lg text-foreground mb-2">9. Contact</h2>
            <p>For questions about these Terms of Service, contact us at oraclebullai@gmail.com.</p>
          </section>
        </div>
      </div>
    </Layout>
  );
};

export default Terms;
