// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-token-price.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var get_token_price_default = defineTool({
  name: "get_token_price",
  title: "Get token price",
  description: "Fetch the current USD price, 24h change, market cap, and volume for a cryptocurrency by CoinGecko id (e.g. 'bitcoin', 'ethereum', 'ethena').",
  inputSchema: {
    coin_id: z.string().min(1).describe("CoinGecko coin id, lowercase (e.g. 'bitcoin', 'ethereum').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ coin_id }) => {
    const url = `https://api.coingecko.com/api/v3/simple/price?ids=${encodeURIComponent(
      coin_id
    )}&vs_currencies=usd&include_market_cap=true&include_24hr_vol=true&include_24hr_change=true`;
    const res = await fetch(url);
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Failed to fetch price (${res.status})` }],
        isError: true
      };
    }
    const json = await res.json();
    const data = json[coin_id];
    if (!data) {
      return {
        content: [{ type: "text", text: `Unknown coin id: ${coin_id}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: {
        coin_id,
        price_usd: data.usd,
        market_cap_usd: data.usd_market_cap,
        volume_24h_usd: data.usd_24h_vol,
        change_24h_pct: data.usd_24h_change
      }
    };
  }
});

// src/lib/mcp/tools/get-trending-tokens.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_trending_tokens_default = defineTool2({
  name: "get_trending_tokens",
  title: "Get trending tokens",
  description: "Fetch the top trending cryptocurrencies right now (by search volume on CoinGecko).",
  inputSchema: {
    limit: z2.number().int().min(1).max(15).optional().describe("Max number of trending tokens to return (default 7).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ limit }) => {
    const res = await fetch("https://api.coingecko.com/api/v3/search/trending");
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Failed to fetch trending (${res.status})` }],
        isError: true
      };
    }
    const json = await res.json();
    const coins = (json.coins ?? []).slice(0, limit ?? 7).map((c) => ({
      id: c.item?.id,
      name: c.item?.name,
      symbol: c.item?.symbol,
      market_cap_rank: c.item?.market_cap_rank,
      price_btc: c.item?.price_btc
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(coins) }],
      structuredContent: { trending: coins }
    };
  }
});

// src/lib/mcp/tools/search-tokens.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var search_tokens_default = defineTool3({
  name: "search_tokens",
  title: "Search cryptocurrencies",
  description: "Search for cryptocurrencies by name or symbol. Returns matching coins with their CoinGecko id, useful for feeding into get_token_price.",
  inputSchema: {
    query: z3.string().min(1).describe("Search query, e.g. 'sol' or 'ethena'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query }) => {
    const res = await fetch(
      `https://api.coingecko.com/api/v3/search?query=${encodeURIComponent(query)}`
    );
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Search failed (${res.status})` }],
        isError: true
      };
    }
    const json = await res.json();
    const coins = (json.coins ?? []).slice(0, 10).map((c) => ({
      id: c.id,
      name: c.name,
      symbol: c.symbol,
      market_cap_rank: c.market_cap_rank
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(coins) }],
      structuredContent: { results: coins }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "oracle-bull-mcp",
  title: "Oracle Bull MCP",
  version: "0.1.0",
  instructions: "Read-only crypto market tools from Oracle Bull. Use `search_tokens` to resolve a symbol to a CoinGecko id, `get_token_price` for live price/market data, and `get_trending_tokens` for what is trending right now.",
  tools: [search_tokens_default, get_token_price_default, get_trending_tokens_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
